### ISSUE TITLE
RSAT : Generated Valid Certificate and While Run the Test case through RSAT , Getting the Error Message : There was no endpoint listening at " " that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. The remote name could not be resolved

### ISSUE THREAD

**Issue by Sarveshwara** [MicrosoftDocs/dynamics-365-unified-operations-public#2091]
1. All Mandatory Prerequisites and SOAP Host Name and Host Name were Provided of TEST Env.
2. **Configure the test environment to trust the connection** were established by updating wif.cofig file with the generated thumbprint. Also the generated certificate is a CSP Key.
3. Ran the following PowerShell scripts on the client computer where the test tool is installed.
Set-ItemProperty HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 -Name SchUseStrongCrypto -Value 1 -Type dword -Force -Confirm:$false

if ((Test-Path HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319))  { Set-ItemProperty HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319 -Name SchUseStrongCrypto -Value 1 -Type dword -Force -Confirm:$false}

4. **Status: Test case failed.**
ERROR:
<Message>The type initializer for 'MS.Dynamics.TestTools.CloudCommonTestUtilities.Authentication.UserManagement' threw an exception.</Message>
<Message>There was no endpoint listening at "https:/" that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.</Message>
<Message>The remote name could not be resolved: </Message>

DEBUG INFO:

<?xml version="1.0" encoding="utf-16"?>

<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<ExceptionType>System.TypeInitializationException</ExceptionType>

<Message>The type initializer for 'MS.Dynamics.TestTools.CloudCommonTestUtilities.Authentication.UserManagement' threw an exception.</Message>

<StackTrace> at MS.Dynamics.TestTools.CloudCommonTestUtilities.Authentication.UserManagement.get_AdminUser()

at MS.Dynamics.Performance.Application.TaskRecorder.Open_ProjectsBase.TestSetup(Boolean verboseSnapshotsEnabled, Int32 actionTimeout, Boolean caseSensitiveValidation, Boolean groupComparison, Int32 pauseBetweenActions)</StackTrace>

<InnerError>

<ExceptionType>System.ServiceModel.EndpointNotFoundException</ExceptionType>

<Message>There was no endpoint listening at "https:/"  that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.</Message>

<StackTrace>

Server stack trace: 

at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()

at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)

at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)

at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)

at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)

at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)

at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)

at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)

at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 

at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)

at MS.Dynamics.TestTools.CloudCommonTestUtilities.AxUserManagementServiceReference.IAxUserManagement.EnumUsers()

at MS.Dynamics.TestTools.CloudCommonTestUtilities.Authentication.UserManagement.PopulateAxUsers()

at MS.Dynamics.TestTools.CloudCommonTestUtilities.Authentication.UserManagement..cctor()</StackTrace>

<InnerError>

<ExceptionType>System.Net.WebException</ExceptionType>

<Message>The remote name could not be resolved: </Message>

<StackTrace> at System.Net.HttpWebRequest.GetRequestStream(TransportContext&amp; context)

at System.Net.HttpWebRequest.GetRequestStream()

at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()</StackTrace>

</InnerError>

</InnerError>

</Error>

**Comment by tonyafehr** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
