### ISSUE TITLE
Admin rights?!

### ISSUE THREAD

**Issue by logicchild** [MicrosoftDocs/dynamics-365-unified-operations-public#251]
Hi, I need to deploy an application deployable package in VM, however I don't have the admin rights, I failed to run the AXUpdateInstaller.exe devinstall command; unable to stop AOSService! (Failed to find the AOS website name.), it seems accessing the IIS API's needs administrative privileges! 
please advice.

Environment: D365 for operation 8.0 Update 15
Package file: D365 for operation 8.0 Update 15 (same version)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b080cde1-a8b7-2677-9de1-df7fd1c13467
* Version Independent ID: 932204fa-5988-997a-530b-1985646517ba
* Content: [Install a deployable package - Finance & Operations | Dynamics 365 | #MSDyn365FO](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/install-deployable-package)
* Content Source: [articles/dev-itpro/deployment/install-deployable-package.md](https://github.com/MicrosoftDocs/Dynamics-365-Unified-Operations-Public/blob/live/articles/dev-itpro/deployment/install-deployable-package.md)
* Service: **dynamics-ax-platform**
* GitHub Login: @manalidongre
* Microsoft Alias: **manado**

**Comment by ShylaThompson** [comment]
Thanks for contacting us. Unfortunately, we can't handle support requests for the product here. To contact support, consider one of the options described here:  https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support

**Comment by sbaber82** [comment]
I am downloaded the AX2012DateUpgrade deployable package and trying to run the command to generate runbook on my local D365 VM, but getting error related to permissions as mentioned below:

Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, AccessControlActions control, String[] fullPathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlSecureResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Microsoft.Dynamics.AX.AXUpdateInstallerBase.TopologyData.InitFromFile(String filePath)
   at Microsoft.Dynamics.AX.AXUpdateInstallerBase.AXUpdateInstallerBase.generate(String runbookID, String topologyFilePath, String serviceModelFilePath, String runbookFilePath, String updatePackageFilePath, IRunbookGenerator runbookGenerator, Boolean generateDVTStep)
   at Microsoft.Dynamics.AX.AXUpdateInstaller.Program.InstallUpdate(String[] args)
   at Microsoft.Dynamics.AX.AXUpdateInstaller.Program.Main(String[] args)

I opened the command prompt as administrator and have all the access to the folder where I extracted the deployable package. Can you please let me know what I am missing here ?

**Comment by AndrewJonesA1X** [comment]
You probably didn't unblock the zip file. That's the error I got when I missed that step.
